export interface RegionInfo {
  id: string;
  label: string;
  description: string;
  curriculumLabel: string;
  conventionsHint: string;
  subjects: string[];
  yearGroups: { value: string; label: string }[];
}

const yg = (value: string, label: string) => ({ value, label });

export const REGIONS: RegionInfo[] = [
  {
    id: "us",
    label: "United States",
    description: "Common Core / state standards.",
    curriculumLabel: "Common Core and US state standards",
    conventionsHint:
      "Use US spelling, US-style examples, and reference Common Core or relevant state standards where applicable. Use grade-level vocabulary (e.g. Grade 7).",
    subjects: [
      "Mathematics",
      "English Language Arts",
      "Science",
      "Biology",
      "Chemistry",
      "Physics",
      "Earth and Space Science",
      "Social Studies",
      "US History",
      "World History",
      "Civics and Government",
      "Geography",
      "Economics",
      "Computer Science",
      "Health",
      "Physical Education",
      "Visual Arts",
      "Music",
      "Theater",
      "Spanish",
      "French",
      "Mandarin",
    ],
    yearGroups: [
      yg("K", "Kindergarten"),
      yg("1", "Grade 1"),
      yg("2", "Grade 2"),
      yg("3", "Grade 3"),
      yg("4", "Grade 4"),
      yg("5", "Grade 5"),
      yg("6", "Grade 6"),
      yg("7", "Grade 7"),
      yg("8", "Grade 8"),
      yg("9", "Grade 9"),
      yg("10", "Grade 10"),
      yg("11", "Grade 11"),
      yg("12", "Grade 12"),
    ],
  },
  {
    id: "uk",
    label: "United Kingdom",
    description: "National Curriculum / GCSE / A-Level.",
    curriculumLabel: "UK National Curriculum, GCSE, and A-Level",
    conventionsHint:
      "Use UK spelling, UK-style examples, and reference Key Stages, GCSE, or A-Level specifications where appropriate. Use 'maths' not 'math'.",
    subjects: [
      "Mathematics",
      "English Language",
      "English Literature",
      "Combined Science",
      "Biology",
      "Chemistry",
      "Physics",
      "History",
      "Geography",
      "Religious Education",
      "Modern Foreign Languages",
      "French",
      "Spanish",
      "German",
      "Computing",
      "Design and Technology",
      "Art and Design",
      "Music",
      "Drama",
      "Physical Education",
      "PSHE",
      "Citizenship",
      "Business Studies",
    ],
    yearGroups: [
      yg("Reception", "Reception"),
      yg("Y1", "Year 1"),
      yg("Y2", "Year 2"),
      yg("Y3", "Year 3"),
      yg("Y4", "Year 4"),
      yg("Y5", "Year 5"),
      yg("Y6", "Year 6"),
      yg("Y7", "Year 7"),
      yg("Y8", "Year 8"),
      yg("Y9", "Year 9"),
      yg("Y10", "Year 10"),
      yg("Y11", "Year 11"),
      yg("Y12", "Year 12"),
      yg("Y13", "Year 13"),
    ],
  },
  {
    id: "europe",
    label: "Europe",
    description: "IB and national European curricula.",
    curriculumLabel:
      "International Baccalaureate and national European curricula",
    conventionsHint:
      "Use British/international English. Default to IB conceptual framing where appropriate. Cite typical European curriculum stages where relevant.",
    subjects: [
      "Mathematics",
      "Language A (Literature)",
      "Language A (Language and Literature)",
      "Language B",
      "Biology",
      "Chemistry",
      "Physics",
      "Environmental Systems and Societies",
      "History",
      "Geography",
      "Economics",
      "Philosophy",
      "Psychology",
      "Computer Science",
      "Design Technology",
      "Visual Arts",
      "Music",
      "Theatre",
      "Physical Education",
      "Theory of Knowledge",
    ],
    yearGroups: [
      yg("PYP1", "PYP 1"),
      yg("PYP2", "PYP 2"),
      yg("PYP3", "PYP 3"),
      yg("PYP4", "PYP 4"),
      yg("PYP5", "PYP 5"),
      yg("MYP1", "MYP 1"),
      yg("MYP2", "MYP 2"),
      yg("MYP3", "MYP 3"),
      yg("MYP4", "MYP 4"),
      yg("MYP5", "MYP 5"),
      yg("DP1", "DP Year 1"),
      yg("DP2", "DP Year 2"),
    ],
  },
  {
    id: "africa",
    label: "Africa",
    description: "National curricula across the continent.",
    curriculumLabel:
      "National curricula across African states (e.g. CBC in Kenya, NERDC in Nigeria, CAPS in South Africa)",
    conventionsHint:
      "Use clear international English. Where relevant, draw on local context, names, and examples. Reference local curriculum frameworks (CBC, CAPS, NERDC) where the teacher indicates.",
    subjects: [
      "Mathematics",
      "English",
      "Integrated Science",
      "Biology",
      "Chemistry",
      "Physics",
      "Agricultural Science",
      "Social Studies",
      "History",
      "Geography",
      "Religious Studies",
      "Civic Education",
      "Life Skills",
      "Kiswahili",
      "French",
      "Portuguese",
      "Arabic",
      "Information and Communication Technology",
      "Business Studies",
      "Home Economics",
      "Creative Arts",
      "Physical Education",
    ],
    yearGroups: [
      yg("PP1", "Pre-Primary 1"),
      yg("PP2", "Pre-Primary 2"),
      yg("P1", "Primary 1"),
      yg("P2", "Primary 2"),
      yg("P3", "Primary 3"),
      yg("P4", "Primary 4"),
      yg("P5", "Primary 5"),
      yg("P6", "Primary 6"),
      yg("JSS1", "Junior Secondary 1"),
      yg("JSS2", "Junior Secondary 2"),
      yg("JSS3", "Junior Secondary 3"),
      yg("SSS1", "Senior Secondary 1"),
      yg("SSS2", "Senior Secondary 2"),
      yg("SSS3", "Senior Secondary 3"),
    ],
  },
  {
    id: "asia",
    label: "Asia",
    description: "National curricula across Asia.",
    curriculumLabel:
      "National curricula across Asia (e.g. CBSE/ICSE in India, MOE Singapore, MEXT Japan, KSSM Malaysia)",
    conventionsHint:
      "Use clear international English. Where relevant, draw on local context, names, and examples. Reference the local curriculum framework where the teacher indicates.",
    subjects: [
      "Mathematics",
      "English",
      "Mother Tongue",
      "Science",
      "Biology",
      "Chemistry",
      "Physics",
      "Social Studies",
      "History",
      "Geography",
      "Economics",
      "Civics",
      "Moral Education",
      "Religious Studies",
      "Hindi",
      "Mandarin",
      "Malay",
      "Tamil",
      "Japanese",
      "Korean",
      "Information Technology",
      "Computer Studies",
      "Art",
      "Music",
      "Physical Education",
    ],
    yearGroups: [
      yg("P1", "Primary 1"),
      yg("P2", "Primary 2"),
      yg("P3", "Primary 3"),
      yg("P4", "Primary 4"),
      yg("P5", "Primary 5"),
      yg("P6", "Primary 6"),
      yg("S1", "Secondary 1"),
      yg("S2", "Secondary 2"),
      yg("S3", "Secondary 3"),
      yg("S4", "Secondary 4"),
      yg("S5", "Secondary 5"),
      yg("JC1", "Junior College 1"),
      yg("JC2", "Junior College 2"),
    ],
  },
];

export function getRegion(id: string): RegionInfo | undefined {
  return REGIONS.find((r) => r.id === id);
}

export const REGION_IDS = REGIONS.map((r) => r.id);
